### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by NachoSoto** [fastlane/watchbuild#8] opened 2015-12-02 18:14 UTC
`tvOS` apps can share a bundle identifier with their `iOS` counterpart, so `watchbuild` can think that the `tvOS` build has already been processed because it finds the `iOS` version.

**Comment by romk1n** [comment] 2015-12-03 19:55
looks like duplicate of #2

**Comment by asfalcone** [comment] 2016-02-23 15:22
Closing as a duplicate.

**Closed by asfalcone** 2016-02-23 15:22 UTC
